django/190322_django_model forms with 1 by N/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.score_delete, name="score_delete"),
    path('<int:movie_pk>/scores/new/', views.scores_create, name="scores_create"),
    path('<int:movie_pk>/edit/', views.update, name="update"),
    path('<int:movie_pk>/delete/', views.delete, name="delete"),
    path('new/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('', views.index, name='index'),
]

django/190322_django_model forms with 1 by N/seed/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/190322_django_model forms with 1 by N/movies/models.py
from django.db import models

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Movie(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=50)
    score = models.IntegerField()
    
    def __str__(self):
        return self.content
    

django/190322_django_model forms with 1 by N/movies/forms.py
from django import forms
from .models import Movie, Score

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={
                'rows': 5,
                'cols': 10,
            }),
            'poster_url': forms.Textarea(attrs={
                'rows': 5,
                'cols': 50,
            }),
            
        }


class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['score', 'content',]
        widgets = {
            'score': forms.NumberInput(attrs={
                'step':1,
                'max':5,
                'min':1,
            })
        }

django/190322_django_model forms with 1 by N/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Genre, Movie, Score
from . import forms
from django.db.models import Avg

# Create your views here.

def index(request):
    # movies = Movie.objects.order_by('-pk')
    movies = get_list_or_404(Movie.objects.annotate(score_avg=Avg('score__score')))
    context = {
        'movies':movies
    }
    return render(request, 'movies/index.html', context)
    
    
def create(request):
    
    if request.method == 'POST':
        form = forms.MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:index')
        
    else:
        form = forms.MovieForm()
    context = {
        'form':form
    }
    return render(request, 'movies/form.html', context)
    

def detail(request, movie_pk):
    
    movie = get_object_or_404(Movie, pk=movie_pk)
    scores = movie.score_set.all()
    form_score = forms.ScoreForm()
    context = {
        'movie': movie,
        'form_score':form_score,
        'scores':scores
    }
    
    
    return render(request, 'movies/detail.html', context)
    
    
def delete(request, movie_pk):
    
    if request.method == "POST":
        movie = get_object_or_404(Movie, pk=movie_pk)
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie_pk)
        
def update(request, movie_pk):
    
    movie = get_object_or_404(Movie, pk=movie_pk)
    
    if request.method == "POST":
        form = forms.MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie_pk)
    else:
        form = forms.MovieForm(instance=movie)
        
    context = {
        'form':form,
        'movie':movie,
    }
    return render(request, 'movies/form.html', context)
    

def scores_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method =="POST":
        score = Score(movie=movie)
        form = forms.ScoreForm(request.POST, instance=score)
        if form.is_valid():
            score = form.save()
            return redirect('movies:detail', movie_pk)
    return redirect('movies:detail', movie_pk)
    
    
def score_delete(request, movie_pk, score_pk):
    
    movie = get_object_or_404(Movie, pk=movie_pk)
    score = get_object_or_404(Score, pk=score_pk)
    
    if request.method =="POST":
        score.delete()
        return redirect('movies:detail', movie_pk)
    return redirect('movies:detail', movie_pk)

django/190322_django_model forms with 1 by N/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} - Movies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
    <div class="container">
        
    {% block body %}
    {% endblock %}
    </div>
<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

django/190322_django_model forms with 1 by N/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<h3>{{movie.title}}</h3>
<hr>
<img src="{{ movie.poster_url }}" alt=poster></img>
<p>장르 : {{movie.genre}}</p>
<p>누적관객수 : {{movie.audience}}</p>
<p>영화 소개 : {{movie.description}}</p>
<p>포스터 url : {{movie.poster_url}}</p>
<div class="d-flex">
<a href="{% url 'movies:index' %}" class="btn btn-primary btn-sm mr-3">뒤로</a><br>
<a href="{% url 'movies:update' movie.pk %}" class="btn btn-info btn-sm mr-3">수정</a><br>
<form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-sm" value="삭제"/>
</form>
</div>
<br>

<form action="{% url 'movies:scores_create' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form_score | crispy }}
    <input type="submit" class="btn btn-primary btn-sm" value="저장"/>
</form>
<br>
<br>
<hr>
{% for score in scores %}
<div class="row justify-content-center">
<div class="col-8 d-flex justify-content-between align-items-center">
<p class="m-0">{{ score.score }}</p>
<p class="m-0">{{ score.content }}</p>
<form action="{% url 'movies:score_delete' movie.pk score.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제" class="btn btn-danger btn-sm"/>
</form>
</div></div>
<hr>

{% empty %}
<h3>평점이 없습니다</h3>
{% endfor %}
{% endblock %}

django/190322_django_model forms with 1 by N/movies/templates/movies/form.html
{% extends 'movies/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

{% if request.resolver_match.url_name == 'create' %}

<h1>새 영화</h1>

{% else %}

<h1>영화 정보 수정</h1>

{% endif %}


<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-primary" value="저장"/>
</form>

<br>
<br>
{% if request.resolver_match.url_name == 'create' %}

<a href="{% url 'movies:index' %}" class="btn btn-info btn-sm">뒤로</a>

{% else %}

<a href="{% url 'movies:detail' movie.pk %}" class="btn btn-info btn-sm">뒤로</a>

{% endif %}


{% endblock %}

django/190322_django_model forms with 1 by N/movies/templates/movies/index.html
{% extends 'movies/base.html' %} {% block title %} Index {% endblock %} {% block body %}

<h2 class="my-4 text-center">영화</h2>
<hr class="mb-5">
<a href="{% url 'movies:create' %}">새 영화</a>
{% for movie in movies %}
<div class="text-center mb-4">
    <a href="{% url 'movies:detail' movie.pk %}">
    <img src="{{ movie.poster_url }}" alt=poster></img></a>
        <br>
        {% if movie.score_avg %}
        
        {{ movie.title }} - 종합 평점 : 
        
        
        <span> {{ movie.score_avg | floatformat:1 }}</span>
        
        {% else %}
        
        {{ movie.title }}
        
        {% endif %}
        
        
</div>


{% empty %}

{% endfor %}


{% endblock %}