django/190411_fake_instagram/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('password/', views.password, name='password'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

django/190411_fake_instagram/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views




urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/190411_fake_instagram/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=10, blank=True)
    introduction = models.TextField(blank=True)
    
    def __str__(self):
        return self.nickname
        

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

django/190411_fake_instagram/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings



class Hashtag(models.Model):
    content = models.TextField(unique=True)
    
    def __str__(self):
        return self.content



class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    
    def __str__(self):
        return self.content
    
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    file = ProcessedImageField(
        upload_to = '',
        processors=[ResizeToFill(100,100)],
        format = 'JPEG',
        options = {'quality':100},
        )
        

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

django/190411_fake_instagram/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        
        
class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email',]
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction',]
        
        

django/190411_fake_instagram/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import SignupForm, UserCustomChangeForm, ProfileForm
from .models import Profile


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
    
    
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('posts:list')
        
    else:
        form = SignupForm()
    
    context = {
        'form':form
    }

    return render(request, 'accounts/signup.html', context)
    

def login(request):
    if request.user.is_authenticated:
        redirect('posts:list')
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            
            return redirect(request.GET.get('next') or 'posts:list')
        
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/login.html', context)
    
@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:list')
    
    
def people(request, username):
    people = get_object_or_404(get_user_model(), username=username)
    context = {
        'people':people,
    }
    
    return render(request, 'accounts/people.html', context)
    
    
@login_required
def delete(request):
    
    if request.method == "POST":
        request.user.delete()
    return redirect('posts:list')
    
    
@login_required
def update(request):
    
    
    if request.method == "POST":
        user_change_form = UserCustomChangeForm(request.POST, instance=request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('people', request.user.username)
    else:   
        user_change_form = UserCustomChangeForm(instance=request.user)
    
    context = {
        'user_change_form':user_change_form,
    }
    
    return render(request, 'accounts/update.html', context)
    
    
@login_required
def password(request):
    
    if request.method == "POST":
        password_change_form = PasswordChangeForm(request.user, data=request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
    
    context = {
        'password_change_form':password_change_form,
    }
    return render(request, 'accounts/password.html', context)
    

@login_required
def profile_update(request):
    profile = Profile.objects.get_or_create(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
        return redirect('posts:list')
        
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    
    context = {
        'profile_form':profile_form,
    }

    return render(request, 'accounts/profile_update.html', context)
    
    

@login_required
def follow(request, user_pk):
    people = get_object_or_404(get_user_model(), pk=user_pk)
    
    if request.user in people.followers.all():
        people.followers.remove(request.user)
    else:
        people.followers.add(request.user)
    
    return redirect('people', people.username)

django/190411_fake_instagram/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}
<h1>로그인</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="Login" reset="Cancle" %}
    {% endbuttons %}
</form>


<a href="{% provider_login_url 'kakao' method='oauth2' %}" class="btn btn-warning">카카오 로그인</a>

{% endblock %}

django/190411_fake_instagram/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<h1>비밀번호 변경</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form password_change_form %}
    {% buttons submit="Edit" reset="Cancle" %}
    {% endbuttons %}
</form>

<a href="{% url 'people' user.username %}" class="btn btn-info btn-sm ml-3">Back</a>
</div>

{% endblock %}

django/190411_fake_instagram/accounts/templates/accounts/people.html
{% extends 'base.html' %} {% block content %}

<h1 class="text-center">{{ people.username }} 의 프로필</h1>

<div class="jumbotron jumbotron-fluid text-center mb-2 text-white bg-dark">
    <div class="container">
        <h1 class="display-4">{{ people.profile.nickname}}</h1>
        <p class="lead">{{ people.profile.introduction}}</p>
        <hr class="border-white my-4">
        <p class="lead">팔로잉 : {{ people.followings.count }} 팔로워 : {{ people.followers.count }}</p>
        
        {% if user != people %}
        {% if user in people.followers.all %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-outline-primary">Unfollow</a>
        {% else %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-primary">Follow</a>
        {% endif %}
        
        {% endif %}
        
    </div>
</div>


{% if people == user %}
<a href="{% url 'accounts:update' %}" class="badge badge-info">회원수정</a>
<a href="{% url 'accounts:profile_update' %}" class="badge badge-success">프로필 수정</a>
<a href="{% url 'accounts:password' %}" class="badge badge-warning">비밀번호수정</a>
<br> {% endif %}


<h3 class="text-center">{{ people.username }} 이 작성한 게시글</h3>

<div class="row">

    {% for post in people.post_set.all|dictsortreversed:"pk" %}
    <div class="col-4 my-2">
        <div class="card">
            <img src="{{ post.image_set.first.file.url }}" class="card-img-top" alt="{{ post.image_set.first.file }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.content }}</h5>
                <p class="card-text">{{ post.like_users.count }} 명이 좋아합니다.</p>
                <p class="card-text">{{ post.comment_set.count }} 개의 댓글</p>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<hr>
<h3 class="text-center">{{ people.username }} 이 작성한 댓글</h3>
<div class="row">
    {% for comment in people.comment_set.all|dictsortreversed:"pk" %}

    <div class="col-12 my-2">
        <div class="card">
            <div class="card-body">
                <blockquote class="blockquote">
                    <p class="mb-0">{{ comment.post }}</p>
                    <footer class="blockquote-footer">{{ comment }}</footer>
                </blockquote>
            </div>
        </div>
    </div>


    {% endfor %}
</div>
{% endblock %}

django/190411_fake_instagram/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>프로필</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    {% buttons submit="Edit" reset="Cancle" %}
    {% endbuttons %}
</form>

<a href="{% url 'people' user.username %}">Back</a>
{% endblock %}

django/190411_fake_instagram/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<h1>회원가입</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="회원가입" reset="Cancle" %}
    {% endbuttons %}
</form>

{% endblock %}

django/190411_fake_instagram/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h1>회원 정보 수정</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form user_change_form %}
    {% buttons submit="Edit" reset="Cancle" %}
    {% endbuttons %}
</form>

<div class="d-flex">
<form action="{% url 'accounts:delete' %}" method="POST" onsubmit="return confirm('탈퇴하시겠습니까?');">
    {% csrf_token %}
    <input type="submit" value="회원탈퇴" class="btn btn-primary btn-sm"/>
</form>

<a href="{% url 'people' user.username %}" class="btn btn-info btn-sm ml-3">Back</a>
</div>

{% endblock %}