django/190320_django_either/choice/urls.py
from django.urls import path
from . import views


app_name = 'choice'


urlpatterns = [
    path('<int:question_pk>/answer_delete/<int:answer_pk>', views.answer_delete, name='answer_delete'),
    path('<int:question_pk>/new_answer/', views.new_answer, name='new_answer'),
    path('<int:question_pk>/delete/', views.delete, name='delete'),
    path('<int:question_pk>/edit/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
    path('<int:question_pk>/', views.detail, name='detail'),
    path('', views.index, name='index'),
]

django/190320_django_either/either/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('choice/', include('choice.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/190320_django_either/choice/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

def choice_image_path(instance, filename):
    return f'choice/images/{filename}'

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=200)
    select_1 = models.CharField(max_length=200)
    img_1 = ProcessedImageField(
        upload_to = choice_image_path,
        processors = [ResizeToFill(300, 200)],
        format = 'JPEG',
        options = {'quality' : 90},
    )
    select_2 = models.CharField(max_length=200)
    img_2 = ProcessedImageField(
        upload_to = choice_image_path,
        processors = [ResizeToFill(300, 200)],
        format = 'JPEG',
        options = {'quality' : 90},
    )
    
    def __str__(self):
        return self.title
    
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment = models.CharField(max_length=200)
    
    def __str__(self):
        return f'{self.comment}'

django/190320_django_either/choice/views.py
from django.shortcuts import render, redirect
from .models import Question, Answer

# Create your views here.
def index(request):
    questions = Question.objects.all()
    context = {
        'questions' : questions
    }
    return render(request, 'choice/index.html', context)
    
def detail(request, question_pk):
    question = Question.objects.get(pk=question_pk)
    answers = question.answer_set.all()
    if answers:
        first = len(question.answer_set.filter(pick=1))*100 // len(answers)
        second = 100-first
    else:
        first, second = 0, 0
    context = {
        'question' : question,
        'answers' : answers,
        'first' : first,
        'second' : second,
    }
    print('#######', question.img_1)
    return render(request, 'choice/detail.html', context)
    
def new(request):
    if request.method == "POST":
        question = Question()
        question.title = request.POST.get('title')
        question.select_1 = request.POST.get('select_1')
        question.img_1 = request.FILES.get('img_1')
        question.select_2 = request.POST.get('select_2')
        question.img_2 = request.FILES.get('img_2')
        question.save()
        return redirect('choice:index')
    else:
        return render(request, 'choice/new.html')
    
def edit(request, question_pk):
    question = Question.objects.get(pk=question_pk)
    if request.method == "POST":
        question.title = request.POST.get('title')
        question.select_1 = request.POST.get('select_1')
        question.select_2 = request.POST.get('select_2')
        question.save()
        return redirect('choice:detail', question_pk)
    else:
        context = {
            'question' : question,
        }
        return render(request, 'choice/edit.html', context)

def delete(request, question_pk):
    if request.method == "POST":
        question = Question.objects.get(pk=question_pk)
        question.delete()
        return redirect('choice:index')
    else:
        return redirect('choice:index')

def new_answer(request, question_pk):
    if request.method == "POST":
        answer = Answer(question_id=question_pk)
        answer.pick = request.POST.get('pick')
        answer.comment = request.POST.get('comment')
        answer.save()
        return redirect('choice:detail', question_pk)
        
def answer_delete(request, question_pk, answer_pk):
    if request.method == "POST":
        answer = Answer(pk=answer_pk)
        answer.delete()
    return redirect('choice:detail', question_pk)

django/190320_django_either/choice/templates/choice/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}-either project</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Gaegu|Gothic+A1|Nanum+Myeongjo" rel="stylesheet">
    <style type="text/css">
        body {
            
            /*background-image : url(https://cdn.clien.net/web/api/file/F03/7299671/1773c15fb9098e.jpg?w=640&h=1260);*/
            background-image : url({% static 'grass.jpg' %});
            
        }
    </style>
</head>

<body>
    <div class='container'>
        <h1 class="text-center my-4" style="font-family: 'Nanum Myeongjo', serif";>당신의 선택은?</h1>
        <hr> {% block body %} {% endblock %}
    </div>


    <!--<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>-->
    <!--<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

django/190320_django_either/choice/templates/choice/detail.html
{% extends 'choice/base.html' %} {% load static %}{% block body %}

<div class="py-3 px-4 rounded" style="background-color:lightgrey">
    <h3 class="text-center">{{ question.title }}</h3>

    <br>
    <div class="row mb-4 justify-content-center">

        <div class="col col-4 d-flex justify-content-center"><img src="{{ question.img_1.url }}"></div>
        <div class="col col-2 d-flex justify-content-center align-items-center">
            <h1 class="text-center">VS</h1>
        </div>
        <div class="col col-4 d-flex justify-content-center"><img src="{{ question.img_2.url }}"></div>

    </div>
    <div class="row mb-4 justify-content-center">

        <div class="col col-4 d-flex justify-content-center">
            <h5>{{ question.select_1 }}</h5>
        </div>
        <div class="col col-2 d-flex justify-content-center align-items-center"></div>
        <div class="col col-4 d-flex justify-content-center">
            <h5>{{ question.select_2 }}</h5>
        </div>

    </div>



    <div class="row justify-content-center">
        <div class="col col-10">



            {% if first == 0 and second == 0%}
            <p class="text-center">의견을 적어주세요!</p>
            {% else %}
            <div class="progress">
                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ first }}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{ question.select_1 }} - {{ first }}%</div>
                <div class="progress-bar bg-danger progress-bar-striped" role="progressbar" style="width: {{ second }}%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">{{ question.select_2 }} - {{second}}%</div>
            </div>
            {% endif %}


        </div>
    </div>
</div>

<form action="{% url 'choice:new_answer' question.pk %}" method="POST">
    {% csrf_token %}
    <div class="row justify-content-center mt-5">
        <div class="btn-group-toggle col-8 row justify-content-center" data-toggle="buttons" style="width: 30%; height: 6rem;">
            <label class="d-flex btn btn-primary text-white justify-content-center align-items-center col-5">
            <input type="radio" name="pick" value="1" autocomplete="off"> {{ question.select_1 }}
            </label>
            <label class="d-flex btn btn-danger text-white justify-content-center align-items-center col-5">
            <input type="radio" name="pick" value="0" autocomplete="off"> {{ question.select_2 }}
            </label>
        </div>
        <div class="form-group col-12 d-flex mt-4 mb-3">
            <input type="text" class="form-control mx-3" name="comment" placeholder="의견을 적어주세요" />
            <input type="submit" class="btn btn-primary mr-3" value="Submit" />
        </div>
    </div>
</form>
<div style="background-color:rgba(0, 10, 50, 0.4);; background-blend-mode:darker" class="ml-2 rounded">
<hr> {% for answer in answers %} {% if answer.pick == 1 %}

<div class="row mx-3 align-items-center">
    <div class="col-2 text-left pl-3"><span class="badge badge-primary">{{ question.select_1 }}</span></div>
    
    <div class="col-9 text-left text-white p-0"> {{ answer.comment }}</div>

    <form action="{% url 'choice:answer_delete' question.pk answer.pk%}" method="POST" class="col-1 text-right p-0">
        {% csrf_token %}
        <input type="submit" value="delete" class="btn btn-warning btn-sm mr-4" />
    </form>

</div>
<hr> {% else %}

<div class="row mx-3 align-items-center">
    <div class="col-2 text-left pl-3"><span class="badge badge-danger">{{ question.select_2 }}</span></div>
    
    <div class="col-9 text-left text-white p-0"> {{ answer.comment }}</div>

    <form action="{% url 'choice:answer_delete' question.pk answer.pk%}" method="POST" class="col-1 text-right p-0">
        {% csrf_token %}
        <input type="submit" value="delete" class="btn btn-warning btn-sm mr-4" />
    </form>

</div>
<hr> {% endif %} {% empty %}
<h5 class="text-center my-3 py-3 text-white">댓글이 없습니다</h5>
{% endfor %}
</div>

<div class="d-flex mb-5">
    <a class="btn btn-info btn-sm mr-1 ml-3 ml-auto" href="{% url 'choice:index' %}" role="button">뒤로</a>
    <form action="{% url 'choice:delete' question.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}

django/190320_django_either/choice/templates/choice/edit.html
{% extends 'choice/base.html' %}
{% block body %}

<h3>질문 수정</h3>


<form class="mt-5" method="POST">
    {% csrf_token %}
  <div class="form-group">
    <input type="text" class="form-control" name="title" value="{{ question.title }}">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="select_1" value="{{ question.select_1 }}">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="select_2" value="{{ question.select_2 }}">
  </div>
  <button type="submit" class="btn btn-primary">저장</button>
</form>


{% endblock %}

django/190320_django_either/choice/templates/choice/index.html
{% extends 'choice/base.html' %} {% block body %}
<div class="row justify-content-end">
    <h4 class="col-8 pl-5">주제를 선택하세요</h4>
    <a href="{% url 'choice:new' %}" class="col-4 text-right align-self-end pr-5">new</a>
</div>
<hr>


<table class="table table-dark">
    <theadclass="table table-light table-bordered">
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="text-center">TOPIC</th>
            <th scope="col" class="text-center">EDIT</th>
            <th scope="col" class="text-center">DELETE</th>
            </th>
        </tr>
    </thead>

    <tbody class="table table-light">
        {% for question in questions %}
        <tr>

            <th scope="row" class="text-center py-3">{{ question.pk }}</th>
            <td class="text-center py-3"><a href="{% url 'choice:detail' question.pk %}">{{ question }}</a></td>
            <td class="text-center py-3"><a href="{% url 'choice:edit' question.pk %}" role="button" class="btn btn-info btn-sm">수정</a></td>
            <td class="text-center py-3">
                <form action="{% url 'choice:delete' question.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="삭제" class="btn btn-danger btn-sm" />
                </form>
            </td>
        </tr>
        {% empty %}
        <tr>
            
            <td class="text-center py-4" colspan="4"><h3>토픽이 없습니다</h3></td>
        </tr>


        {% endfor %}



    </tbody>
</table>


<hr> {% endblock %}

django/190320_django_either/choice/templates/choice/new.html
{% extends 'choice/base.html' %}

{% block body %}

<h3 >새로운 질문</h3>
<h5 class='text-right' style="font-family: 'Gaegu', cursive;">새 질문을 등록하려구? 정말 데단해</h5>
<form class="mt-5" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="form-group">
    <label for="title">주제를 적어주세요</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="주제를 적어주세요">
  </div>
  <div class="form-group">
    <label for="select_1">첫번째 주장</label>
    
    <input type="text" class="form-control" id="select_1" name="select_1" placeholder="첫번째 주장"><br>
    <label for="img_1">관련 사진</label><br>
    <input type="file" name="img_1" id="img_1" accept="image/*"/>
  </div>
  <br>
  <div class="form-group">
    <label for="select_2">두번째 주장</label>
    <input type="text" class="form-control" id="select_2" name="select_2" placeholder="두번째 주장"><br>
    <label for="img_2">관련 사진</label><br>
    <input type="file" name="img_2" id="img_1" accept="image/*"/>
  </div>
  <br>
  <div class="d-flex">
    <button type="submit" class="btn btn-primary ml-auto">저장</button>
  </div>
</form>


{% endblock %}