django/190408_django_account/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('<int:user_pk>/', views.profile, name="profile"),
    path('password/', views.change_password, name="change_password"),
    path('edit/', views.edit, name="edit"),
    path('delete/', views.delete, name="delete"),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
]

django/190408_django_account/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'


urlpatterns = [
    path('<int:board_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:board_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:board_pk>/edit/', views.update, name="update"),
    path('<int:board_pk>/delete/', views.delete, name="delete"),
    path('<int:board_pk>/', views.detail, name="detail"),
    path('new/', views.create, name="create"),
    path('', views.index, name="index"),
]

django/190408_django_account/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

django/190408_django_account/boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
        
        
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

django/190408_django_account/boards/forms.py
from django import forms
from .models import Board, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# class BoardForm(forms.Form):
#     title = forms.CharField(label="제목", widget=forms.TextInput(attrs={
#         'placeholder':'THE TITLE!'
#     }))
#     content = forms.CharField(label="내용",
#     error_messages = {'required':'제발 내용을 입력해주세요'},
#     widget=forms.Textarea(attrs={
#         'class':'Content-input',
#         'rows':5,
#         'cols':50,
#         'placeholder':'Fill the content'
        
#     }))

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content']
        widgets= {'title' : forms.TextInput(attrs={
                                                'placeholder':'제목을 입력하세요.',
                                                'class':'title',}),
                'content': forms.Textarea(attrs={
                                                'placeholder':'내용을 입력하세요.',
                                                'class':'content',
                                                'rows':5,
                                                'cols':50,})}
        error_messages = {'title': {
                                'required':'제발 입력하세요',},
                        'content': {'required':'빈칸이 있습니다',},
                        }
                        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', '작성!'))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        

django/190408_django_account/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import Board, Comment
from .forms import BoardForm, CommentForm
import hashlib

# Create your views here.


def index(request):
    
    boards = get_list_or_404(Board.objects.order_by('-pk'))
    
    context = {
        'boards':boards,
    }
    
    return render(request, 'boards/index.html', context)


@login_required
def create(request):
    if request.method =="POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {
        'form':form
    }
    return render(request, 'boards/form.html', context)
        
def detail(request, board_pk):
    
    
    
    board = get_object_or_404(Board, pk=board_pk)
    
    comment_form = CommentForm()
    
    context = {
        'board':board,
        'comment_form':comment_form,
    }
    return render(request, 'boards/detail.html', context)
    
def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)

@login_required
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                board=form.save()
                return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)
    else:
        return redirect('boards:index')
    
    context = {
        'form':form,
        'board':board,
    }
    return render(request, 'boards/form.html', context)
            
        

@require_POST   
@login_required
def comment_create(request, board_pk):
    form = CommentForm(request.POST)
    
    if form.is_valid():
        comment = form.save(commit=False)
        
        comment.user = request.user
        comment.board_id = board_pk
        comment.save()
    
    return redirect('boards:detail', board_pk)
        
        
    # board = Board.objects.get(pk=board_pk)
    # user = request.user
    # content = request.POST.get('content')
    # comment = Comment(board=board, content=content, user=user)
    # comment.save()
    # return redirect('boards:detail', board.pk)


@login_required
@require_POST
def comment_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('boards:detail', board_pk)
    
    
    # comment = Comment.objects.get(pk=comment_pk)
    # if request.method =='POST':
    #     comment.delete()
    #     return redirect('boards:detail', board_pk)
    # else:
    #     return redirect('boards:detail', board_pk)
    

django/190408_django_account/boards/templates/boards/base.html
{% load gravatar %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}- form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <h5><a href="{% url 'boards:index' %}">HOME</a></h5>
        {% if user.is_authenticated %}
        <div class="d-flex">
            <img src="https://s.gravatar.com/avatar/{{ user.email | makemd5 }}?s=80" alt="avatar">
            <h5 class="text-right text-secondary">안녕, <a href="{% url 'accounts:profile' user.pk %}">{{user.username}}</a>
                <a href="{% url 'accounts:logout' %}">로그아웃</a></h5>
        </div>
        {% else %}
        <h5 class="text-right text-primary"><a href="{% url 'accounts:login' %}">로그인</a> <a href="{% url 'accounts:signup' %}">회원가입</a></h5>
        {% endif %}
        <hr> {% block body %} {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

django/190408_django_account/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% load crispy_forms_tags %}


{% block title %}
Index
{% endblock %}

{% block body %}
<h1>{{ board.pk }} 번째 글</h1>
<h2>{{ board.title }}</h2>
<hr>
<p>{{ board.content }}</p>
<a href="{% url 'boards:index' %}">뒤로</a>

{% if user == board.user %}

<a href="{% url 'boards:update' board.pk  %}">수정</a>
<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제"/>
</form>

{% endif %}



{% if user.is_authenticated %}

<form method="POST" action="{% url 'boards:comment_create' board.pk %}">
    {% csrf_token %}
    {{ comment_form | crispy }}
    <input type="submit" value="Submit"/>
</form><br>


{% else %}
<div>댓글을 작성하려면<a href="{% url 'accounts:login' %}">로그인</a>하세요</div>

{% endif %}





{% for comment in board.comment_set.all %}

<div class="d-flex">
    <span>{{ comment.user }} : {{comment}}</span>
    
    {% if user == comment.user %}
    <form action="{% url 'boards:comment_delete' board.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="delete"/>
        {% endif %}
    </form>
    
    
</div><hr>
{% empty %}
<div>댓글이 없습니다.</div>

{% endfor %}
{% endblock %}

django/190408_django_account/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
New
{% endblock %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}

<h1>New Board</h1>

{% else %}

<h1>Edit Board</h1>

{% endif %}



<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Submit"/>
</form><br>


<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ form.title }}-->
<!--    {{ form.content }}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form><br>-->


<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    {% for field in form %}-->
<!--        {{ field.errors }}-->
<!--        {{ field.label_tag }} {{ field }}-->
        
<!--    {% endfor %}-->
    
<!--    <input type="submit" value="Submit"/>-->
<!--</form><br>-->


<!--{{ form.non_field_errors }}-->
<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    <div>-->
<!--        {{ form.title.errors }}-->
<!--        {{ form.title.label_tag }}-->
<!--        {{ form.title }}-->
<!--    </div>-->
<!--    <div>-->
<!--        {{ form.content.errors }}-->
<!--        {{ form.content.label_tag }}-->
<!--        {{ form.content }}-->
<!--    </div>-->
    
<!--    <input type="submit" value="Submit"/>-->
<!--</form><br>-->


<!--{{ form.non_field_errors }}-->
<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    <div>-->
<!--        {{ form.title.errors }}-->
<!--        {{ form.title.label_tag }}-->
<!--        {{ form.title }}-->
<!--    </div>-->
<!--    <div>-->
<!--        {{ form.content.errors }}-->
<!--        {{ form.content.label_tag }}-->
<!--        {{ form.content }}-->
<!--    </div>-->
    
<!--    <input type="submit" value="Submit"/>-->
<!--</form><br>-->

<!--{% crispy form %}-->

{% if request.resolver_match.url_name == 'create' %}

<a href="{% url 'boards:index' %}">뒤로</a>

{% else %}

<a href="{% url 'boards:detail' board.pk %}">뒤로</a>

{% endif %}


{% endblock %}

django/190408_django_account/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block title %}
Index
{% endblock %}

{% block body %}
<h1>게시글 목록</h1>
<br>
{% if user.is_authenticated %}
<a href="{% url 'boards:create' %}">새 글</a>
{% else %}
<p>새 글을 작성하려면 <a href="{% url 'accounts:login' %}">로그인</a>하세요</p>
{% endif %}

<hr>
{% for board in boards %}
<p><b>작성자 : <a href="{% url 'accounts:profile' board.user.pk %}">{{ board.user }}</a></b></p>
<p>{{ board.pk }}</p>
<p><a href="{% url 'boards:detail' board.pk %}">{{ board.title }}</a></p>

{% empty %}
<h5>게시글이 없습니다</h5>
{% endfor %}
{% endblock %}